### ISSUE TITLE
Validate openapi specification output

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#133]
In in the config.yaml you have:

```yaml
  servers:
    - url: http://localhost:8080/v1
    - description: localhost server
```
then the spec will produce:
```yaml
servers:
 - url: http://localhost:8080/v1
 - description: localhost server
```
which fails according to the openAPI spec. We should validate the full spec before wrapping it up
