### ISSUE TITLE
Limit and pagination

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#61]
It is not clear to me how we support pagination on the system.
For example, if we add an API for DBPedia, we cannot return all Person or Location, as it would be too many. We need a limit (and offset) to do pagination.

**Comment by sirspock** [comment]
We are going to use the same approach of Github 
https://developer.github.com/v3/guides/traversing-with-pagination/


Add two parameters:
```yaml
        -   name: page
            description: The page number
            schema:
                type: integer
                default: 1
            in: query
            required: false
        -
            name: per_page
            description: Items per page
            schema:
                type: integer
                default: 100
                minimum: 1
                maximum: 200
            in: query
            required: false
```

**Comment by sirspock** [comment]
According https://tools.ietf.org/html/rfc5988#page-6, Information about pagination is provided in the Link header

```
          headers:
            link:
              schema:
                type: string
              description: Information about pagination 
```
